eurekaHost: 192.168.0.222
spring:
  application:
    name: licensingservice
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      profile: study
      label: master
      enabled: true
  config:
    import: optional:configserver:""
#    import: configserver:http://localhost:10001
eureka:
  client:
    service-url:
      defaultZone: http://${eurekaHost}:10011/eureka,http://${eurekaHost}:10012/eureka
logging:
  config: classpath:logback-spring.xml
thisenv: ${myenv}