spring:
  application:
    name: licensingservice #  指定许可证服务的名称，以便Spring Cloud Config客户端知道正在查找哪个服务
  profiles:
    active: study
  config:
    import: configserver:http://localhost:10001

logging:
  config: classpath:logback-spring.xml

thisenv: ${myenv}