spring:
  application:
    name: gatewayserver
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      profile: study
      label: master
      enabled: true
  config:
    import: optional:configserver:""
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10011/eureka,http://127.0.0.1:10012/eureka
