cloud-host: 192.168.0.222
spring:
  application:
    name: gatewayserver
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      profile: study
      label: master
      enabled: true
  config:
    import: optional:configserver:""
eureka:
  client:
    service-url:
      defaultZone: http://${cloud-host}:10011/eureka,http://${cloud-host}:10012/eureka
