spring:
  application:
    name: gatewayserver
  profiles:
    active: study
  config:
    import: configserver:http://localhost:10001
  zipkin:
    base-url: http://127.0.0.1:9411/
    sender:
      type: web #传输方式，web,kafka...
  sleuth:
    sampler:
      probability: 1.0 #收集数据百分比，默认0.1
