eurekaHost: 192.168.0.222
server:
  port: 10001

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: git@github.com:yydzxz/private-config.git
          searchPaths: '{application}'
          defaultLabel: master
          basedir: ~/code/cloud-config-basedir
  application:
    name: config-server
management:
  server:
    port: 10002
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaHost}:10011/eureka,http://${eurekaHost}:10012/eureka